language: node_js
node_js:
  - "11"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - yarn global add firebase-tools
  - yarn global add @angular/cli
    
install:
  - yarn install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - ng test --watch=false --browsers ChromeHeadless --code-coverage
  - ./cc-test-reporter format-coverage -t lcov coverage/beefinder/lcov.info
  - ng build --prod

after_script:
  - ./cc-test-reporter upload-coverage

after_success:
- firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT