language: node_js
node_js:
  - "node"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - yarn global add firebase-tools
  - yarn global add @angular/cli
    
install:
  - yarn install

script:
  - ng test --watch=false --browser ChromeHeadless --code-coverage
  - ng build --prod

after_success:
- firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT